module.exports = [
  {
    id: 'kyVarru3AiouGrCO1gZxuw',
    alias: 'iron-horse-coffee-san-francisco-2',
    name: 'Iron Horse Coffee',
    image_url:
      'https://s3-media2.fl.yelpcdn.com/bphoto/CaiOHeV147HoltHAt-soIw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/iron-horse-coffee-san-francisco-2?adjust_creative=Hs-YN8zNU8-U3ox8FrslEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=Hs-YN8zNU8-U3ox8FrslEw',
    review_count: 110,
    categories: [
      {
        alias: 'coffee',
        title: 'Coffee & Tea',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 37.7882923185825,
      longitude: -122.404029965401,
    },
    transactions: ['delivery'],
    price: '$',
    location: {
      address1: '25 Maiden Ln',
      address2: null,
      address3: '',
      city: 'San Francisco',
      zip_code: '94108',
      country: 'US',
      state: 'CA',
      display_address: ['25 Maiden Ln', 'San Francisco, CA 94108'],
    },
    phone: '+14154042877',
    display_phone: '(415) 404-2877',
    distance: 389.21701115431307,
  },
  {
    id: '24ym9XJUS2i9JlSFEJeZ2w',
    alias: 'the-coffee-movement-san-francisco',
    name: 'The Coffee Movement',
    image_url:
      'https://s3-media1.fl.yelpcdn.com/bphoto/TyHWNBOLomkcSCTi3ZZXvA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/the-coffee-movement-san-francisco?adjust_creative=Hs-YN8zNU8-U3ox8FrslEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=Hs-YN8zNU8-U3ox8FrslEw',
    review_count: 294,
    categories: [
      {
        alias: 'coffee',
        title: 'Coffee & Tea',
      },
    ],
    rating: 5.0,
    coordinates: {
      latitude: 37.79483,
      longitude: -122.4103,
    },
    transactions: ['delivery'],
    price: '$$',
    location: {
      address1: '1030 Washington St',
      address2: null,
      address3: '',
      city: 'San Francisco',
      zip_code: '94108',
      country: 'US',
      state: 'CA',
      display_address: ['1030 Washington St', 'San Francisco, CA 94108'],
    },
    phone: '',
    display_phone: '',
    distance: 1271.617705174058,
  },
  {
    id: 'BrGq6WWjVNM8h44KPKl0Xw',
    alias: 'andytown-coffee-roasters-san-francisco-3',
    name: 'Andytown Coffee Roasters',
    image_url:
      'https://s3-media1.fl.yelpcdn.com/bphoto/rYQqveQXbtmA1egab7Dreg/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/andytown-coffee-roasters-san-francisco-3?adjust_creative=Hs-YN8zNU8-U3ox8FrslEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=Hs-YN8zNU8-U3ox8FrslEw',
    review_count: 67,
    categories: [
      {
        alias: 'coffeeroasteries',
        title: 'Coffee Roasteries',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 37.789744,
      longitude: -122.39531,
    },
    transactions: ['delivery'],
    price: '$$',
    location: {
      address1: '181 Fremont St',
      address2: 'Fl 7',
      address3: null,
      city: 'San Francisco',
      zip_code: '94105',
      country: 'US',
      state: 'CA',
      display_address: ['181 Fremont St', 'Fl 7', 'San Francisco, CA 94105'],
    },
    phone: '+14157539775',
    display_phone: '(415) 753-9775',
    distance: 518.7568658547667,
  },
  {
    id: 'Se1xmgWc4JRWPG5MiZFzNg',
    alias: 'golden-goat-coffee-san-francisco',
    name: 'Golden Goat Coffee',
    image_url:
      'https://s3-media3.fl.yelpcdn.com/bphoto/Hi0qxwxjIhODVsjsoPY09A/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/golden-goat-coffee-san-francisco?adjust_creative=Hs-YN8zNU8-U3ox8FrslEw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=Hs-YN8zNU8-U3ox8FrslEw',
    review_count: 79,
    categories: [
      {
        alias: 'coffee',
        title: 'Coffee & Tea',
      },
    ],
    rating: 5.0,
    coordinates: {
      latitude: 37.78044,
      longitude: -122.39425,
    },
    transactions: [],
    location: {
      address1: '599 3rd St',
      address2: '',
      address3: null,
      city: 'San Francisco',
      zip_code: '94107',
      country: 'US',
      state: 'CA',
      display_address: ['599 3rd St', 'San Francisco, CA 94107'],
    },
    phone: '',
    display_phone: '',
    distance: 871.463887904591,
  },
];
